services:
  antifraud:
    container_name: yp_antifraud
    platform: linux/amd64
    build:
      context: ./antifraud-service
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      kafka:
        condition: service_healthy
